### ISSUE TITLE
NSNotificationCenter.defaultNotificationCenter returns None

### ISSUE THREAD

**Issue by erisdev** [azadkuh/cmus-osx#11]
i get this funny little error when i run install.py. traced it back to `NSNotificationCenter.defaultNotificationCenter` returning `None` instead of, you know.

```
Traceback (most recent call last):
  File "/Users/eris/.config/cmus/cmus-osx/notify.py", line 146, in <module>
    center.removeAllDeliveredNotifications()
AttributeError: 'NoneType' object has no attribute 'removeAllDeliveredNotifications'
```

media keys functionality works fine.

* python 3.5.1 
* pyenv 1.1.0
* macos 10.12.5

**Comment by PhilipTrauner** [comment]
Huh, that's interesting. Haven't been able to reproduce yet, but I'm still working on it. I'm assuming pyenv is the culprit here, though.

**Comment by PhilipTrauner** [comment]
```python
from Foundation import NSUserNotificationCenter
from Foundation import NSUserNotification

center = NSUserNotificationCenter.defaultUserNotificationCenter()
notification = NSUserNotification.alloc().init()

notification.setTitle_("Title")
notification.setSubtitle_("Subtitle")
notification.setInformativeText_("Informative Text")

center.removeAllDeliveredNotifications()
center.deliverNotification_(notification)
```

Please execute this code segment with your default python3 interpreter to make troubleshooting a little bit easier for me. A notification ***should*** pop up, if it doesn't something is wrong with your python setup.

**Comment by erisdev** [comment]
solved it. turns out python has to be built with `--enable-framework`. pyenv users should add this to their `.bashenv`/`.zshenv`/whatever, then reinstall their pyenv python:

```shell
export PYTHON_CONFIGURE_OPTS="--enable-framework"
```

you should prolly add this to the readme somewhere for future pyenv users like me.

---

a little more context: `+[NSNotificationCenter defaultNotificationCenter]` is an elitist that will only return a notification center object if the calling function lives inside a bundle or a library that has been loaded by a bundle, be it a framework, application or loadable bundle. also, the bundle (except frameworks?) needs to have an info.plist with a `CFBundleIdentifier` key 🎫 or it doesn't count.

by default python builds as a plain ol dynamic library (i think—my old python was at least) which means the whole python interpreter lives in a dylib with a command line program that links to it. python C extensions (like pyobjc) are built as naked loadable libraries with no info.plist. that means no proper _bundles_ in the call stack 💀 which means `NSNotificationCenter` ain't your friend. 💦💦

so that's where `PYTHON_CONFIGURE_OPTS` comes in. `--enable-framework` builds the python interpreter as a framework rather than a dylib, which means ⚡️ now there's a bundle in the call stack. ✨ `NSNotificationCenter` recognizes you as a member of its little club ✨

at least, that's how i understand the problem. so it looks like anybody who uses pyobjc should have ⬆️ that environment variable ⬆️ set. no telling what other goofs building python without it might cause in objc land.

**Comment by PhilipTrauner** [comment]
@erisdev Thanks for the research, would have taken ages to debug. 😆
