### ISSUE TITLE
media keys not working

### ISSUE THREAD

**Issue by liviurad** [azadkuh/cmus-osx#13]
I installed it. Notifications are working, but media keys not. iTunes is not staring anymore, which is nice :), but cmus is also doing nothing. Do I miss something?

- running macOS Sierra 10.12.6
- pyenv and python3 installed with brew

**Comment by PhilipTrauner** [comment]
Kinda reminds me of #11, and I think I know what the problem is. 

Please run this code snippet, press your media keys and comment with the output generated by it. If a valid media key is pressed the program should print the name of the key, otherwise 'Unknown key code' is displayed. My assumption is that the constants used to detect media keys don't apply to your setup (third party keyboard perhaps). 

```python
from AppKit import NSApplication, NSApplicationActivationPolicyProhibited
from AppKit import NSSystemDefined
from AppKit import NSKeyUp
from PyObjCTools import AppHelper

class KeySocketApp(NSApplication):
	repeated = False

	def sendEvent_(self, event):
		if event.type() is NSSystemDefined and event.subtype() is 8:
			data = event.data1()
			key_code = (data & 0xFFFF0000) >> 16
			key_flags = (data & 0x0000FFFF)
			key_state = (key_flags & 0xFF00) >> 8
			key_repeat = key_flags & 0x1

		if key_state is NSKeyUp:
			if self.repeated:
				self.repeated = False
		elif key_code == 20 or key_code == 18:
			print("Previous key detected")
		elif key_code == 16:
			print("Play/pause key detected")
		elif key_code == 19 or key_code == 17:
			print("Next key detected.")
		else:
			print("Unknown key code: %i" % key_code)

app = KeySocketApp.sharedApplication()
app.setActivationPolicy_(NSApplicationActivationPolicyProhibited)
AppHelper.runEventLoop()
```

**Comment by liviurad** [comment]
For some reason it didn't work before. Now it works both in the snippet and cmus is reacting as expected. 

BTW I am using indeed an external keyboard, but it is a Apple official/standard wired keyboard.

Thank for you answer :). I was using Cog, but wanted to move to console and this is what I was missing, media keys and notifications ;)

lr@liviu ~/Personal $ python media_keys.py
Next key detected.
Next key detected.
Play/pause key detected
Play/pause key detected
Play/pause key detected
Play/pause key detected
Play/pause key detected
Play/pause key detected
Play/pause key detected
Play/pause key detected
Play/pause key detected

**Comment by PhilipTrauner** [comment]
@liviurad Glad I could help 😌
