### ISSUE TITLE
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

### ISSUE THREAD

**Issue by royaso** [azadkuh/cmus-osx#20]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

-----
is it because I didn't have Xcode installed? I have installed brew

**Comment by PhilipTrauner** [comment]
I'm not entirely sure where you could have encountered that error, but yes, installing Xcode will most likely fix it.
