### ISSUE TITLE
Any plan to support other filetype?

### ISSUE THREAD

**Issue by darkbrow** [azadkuh/cmus-osx#3]
I have a bunch of m4a files in my library.
cmus-osx works perfectly, but album cover doesn't displayed.
Is there any plan to support other filetype?

**Comment by azadkuh** [comment]
well, i use a third party (`eyed3`) to parse `ID3` tags of a song. it seems `eyeD3` does not support anything other than `mp3` (but it's quite performant)

i will try other options like `mutagen` as it supports `m4a`.

**Comment by azadkuh** [comment]
@darkbrow 
FYI, i've replaced `eyeD3` with [`tinytag`](https://github.com/devsnd/tinytag) who supports mp3/m4a/flac/...

it's a very small and clean python lib, and a nice performer.
