### ISSUE TITLE
notify.py not working

### ISSUE THREAD

**Issue by izotomas** [azadkuh/cmus-osx#4]
so, how exactly should notification work? 
should cmus it do it by itself?
i tried to run it manually and i'm getting invalid arguments message...

**Comment by azadkuh** [comment]
you need to install 3rdparty deps, `cmus-osx` and then run

``` bash
$> cmus-osx.py
```

`cmus-osx` then run the `cmus` internally.

**Comment by izotomas** [comment]
I already had cmus-osx, but it still didn't work. music controls(F7-9) are ok, though... anyway, i managed to set up [cmusfm](https://github.com/Arkq/cmusfm), which it works just fine, so it's no longer an issue. thanks

**Comment by azadkuh** [comment]
would you please have a look at: `/tmp/cmus-notify.log`?

**Comment by izotomas** [comment]
well, reinstalled my machine but i remember it was a one liner - invalid arguments...then when i installed it today on a fresh OS it was just an empty file(even after 2-3 songs), then I switched to cmusfm again.

**Comment by izotomas** [comment]
now when i look at it closer i noticed that cmus-osx-keys.py works no more either(was fine yesterday), and notifications never worked. anyway, what do you mean by ?

> cmus-osx then run the cmus internally.

when i run cmus-osx it already launches cmus, so it cannot be launched again...

**Comment by azadkuh** [comment]
> anyway, what do you mean by ...

just wanted to make sure that you'd run the `cmus-osx.py` and not the `cmus` itself (some users forgets)

>  i noticed that cmus-osx-keys.py works no more either ...

if the `iTunes` takes the media keys (you can also check [here](https://github.com/azadkuh/cmus-osx/blob/master/under-the-hood.md#os-x-tips)) :

``` bash
$> launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist
```

and then re-start `cmus-osx`.

FYI, I've tried `cmus-osx` under OS X 10.10.? to 10.11.6, `cmus`up to  v2.7.1, python 2.7.12 (via brew)

**Comment by PhilipTrauner** [comment]
Due to a lack of activity and the complete rewrite of cmus-osx I'll close this issue. Feel free to reopen it if this problem still persists.
