### ISSUE TITLE
Notifications not working after installing pyenv

### ISSUE THREAD

**Issue by oquirozm** [azadkuh/cmus-osx#5]
Hi there!

I love this utility. Works perfect. Yesterday I installed pyenv in order to run some packages with Python 3.5.2. cmus-osx media keys function is still working great but the notifications stopped showing up. I've made sure python 2.7.11 is the one being globally used when I execute cmus-osx.py, but it isn't working.

I'm a newbie programmer, so any idea on how could I make the notifications work again? Or how could I debug it?

Thanks.

**Comment by azadkuh** [comment]
@oquirozm 
please have look at: `/tmp/cmus-notify.log`

you can also simply add your own log messages into `/_installation_path_/cmus-osx-notify.py` and evaluate the problem. for example: [here](https://github.com/azadkuh/cmus-osx/blob/master/bin/cmus-osx-notify.py#L7-L8) and [here](https://github.com/azadkuh/cmus-osx/blob/master/bin/cmus-osx-notify.py#L60-L63)

**Comment by oquirozm** [comment]
Hi @azadkuh,

I checked the .log and this is what I found:

```
ERROR:root:cmus nottify error!
Traceback (most recent call last):
  File "/usr/local/bin/cmus-osx-notify.py", line 191, in <module>
    noti.show(cmus.title, cmus.subtitle, cmus.message, cmus.cover)
  File "/usr/local/bin/cmus-osx-notify.py", line 156, in show
    center.removeAllDeliveredNotifications()
AttributeError: 'NoneType' object has no attribute 'removeAllDeliveredNotifications'
```

I'm using OS X 10.11.6 and Python 2.7.11. I also made sure that `pyobjc` is installed.

**Comment by azadkuh** [comment]
well i'm not sure but the for some reason the:

``` python
center = NSUserNotificationCenter.defaultUserNotificationCenter()
```

fails on your system (this is a standard method on a `pyobjc` module)

to make sure that this line causes the problem please add these two lines to `Notification.show()` of `cmus-osx-notify.py`(line 139):

``` python
    def show(self, title, subtitle, message, cover):
        center = NSUserNotificationCenter.defaultUserNotificationCenter()
        # add --->
        if not center:
            raise Exception('unable to initialize OS X default user notification center.')
        # <---        
```

then save and re-check the log.

**Comment by oquirozm** [comment]
I didn't test that yet, but I found out something interesting. When I use `pyenv versions` it lists all my python versions:
- system (set by /Users/username/.pyenv/version)
- 2.7.11
- 3.5.2

If I choose system (`pyenv global system`) the notifications show up! If I go back to any of the versions I installed using `pyenv` the fail to show up. Not sure what is this supposed to mean.

**Comment by azadkuh** [comment]
hmmm, you may need to reinstall (share) dependencies (`pyobjc` and `tinytag`) on every environment who launches the `cmus-osx`.

**Comment by azadkuh** [comment]
@oquirozm 
if you find a solution for your problem please share it and close this issue.

**Comment by PhilipTrauner** [comment]
Due to a lack of activity and the complete rewrite of cmus-osx I'll close this issue. Feel free to reopen it if this problem still persists.
