### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by benyomin** [azadkuh/cmus-osx#6]
I get this when installing your requirement
`pip install -U pyobjc`

**Comment by azadkuh** [comment]
well, this is a python/pip installation issue and irrelevant to `cmus-osx`.
i hope [this link](http://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c) will help.
