### ISSUE TITLE
Itunes start automatically

### ISSUE THREAD

**Issue by justijndepover** [azadkuh/cmus-osx#9]
When pressing the play button, iTunes opens automatically. Is it possible to prevent this?
I know i can disable that feature for iTunes but if i use something like mpsyt it works just fine (without opening iTunes)

**Comment by azadkuh** [comment]
@justijndepover would you please specify your `macos / OS X` version?
and please try the [v1.2.0](https://github.com/azadkuh/cmus-osx/releases/tag/v1.2.0) version and check if the same problem exists.

**Comment by PhilipTrauner** [comment]
Like @azadkuh stated: If this issue persists please switch to  [v1.2.0](https://github.com/azadkuh/cmus-osx/releases/tag/v1.2.0).

Some additional information would be great to fix this issue in the newest version: 
* Which Python version do you have installed as `python3`
* The content of `~/.config/cmus/rc`
* The output of `ps aux | grep python` while cmus is running

**Comment by PhilipTrauner** [comment]
Well, I guess I've spotted the problem:

```bash
launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist
/System/Library/LaunchAgents/com.apple.rcd.plist: Operation not permitted while System Integrity Protection is engaged
```

From macOS 10.12 onwards you can't unload built-in launch agents.

**Comment by PhilipTrauner** [comment]
@justijndepover There are some workaround available if you still want to use cmus-osx after such a long time. [This](https://github.com/herrbischoff/awesome-osx-command-line/issues/134#issuecomment-294185380) is the most convenient one and does not require booting into recovery mode.
